export const ordersDemoData = [
  {
    id: 1,
    buyer: { name: "Muneeb Ahmed", avatar: "/avatars/1.jpg" },
    orderId: "#ORD-2034",
    product: "DAP Fertilizer (25kg)",
    qty: 10,
    orderDate: "12 July 2025",
    total: "PKR 23,000",
    status: "Pending",
  },
  {
    id: 2,
    buyer: { name: "Muneeb Ahmed", avatar: "/avatars/2.jpg" },
    orderId: "#ORD-2034",
    product: "DAP Fertilizer (25kg)",
    qty: 10,
    orderDate: "12 July 2025",
    total: "PKR 23,000",
    status: "Delivered",
  },
  {
    id: 3,
    buyer: { name: "Muneeb Ahmed", avatar: "/avatars/3.jpg" },
    orderId: "#ORD-2034",
    product: "DAP Fertilizer (25kg)",
    qty: 10,
    orderDate: "12 July 2025",
    total: "PKR 23,000",
    status: "Shipped",
  },
  {
    id: 4,
    buyer: { name: "Muneeb Ahmed", avatar: "/avatars/4.jpg" },
    orderId: "#ORD-2034",
    product: "DAP Fertilizer (25kg)",
    qty: 10,
    orderDate: "12 July 2025",
    total: "PKR 23,000",
    status: "Cancelled",
  },
  {
    id: 5,
    buyer: { name: "Muneeb Ahmed", avatar: "/avatars/5.jpg" },
    orderId: "#ORD-2034",
    product: "DAP Fertilizer (25kg)",
    qty: 10,
    orderDate: "12 July 2025",
    total: "PKR 23,000",
    status: "Delivered",
  },
  {
    id: 6,
    buyer: { name: "Muneeb Ahmed", avatar: "/avatars/6.jpg" },
    orderId: "#ORD-2034",
    product: "DAP Fertilizer (25kg)",
    qty: 10,
    orderDate: "12 July 2025",
    total: "PKR 23,000",
    status: "Cancelled",
  },
  {
    id: 7,
    buyer: { name: "Muneeb Ahmed", avatar: "/avatars/7.jpg" },
    orderId: "#ORD-2034",
    product: "DAP Fertilizer (25kg)",
    qty: 10,
    orderDate: "12 July 2025",
    total: "PKR 23,000",
    status: "Shipped",
  },
  {
    id: 8,
    buyer: { name: "Muneeb Ahmed", avatar: "/avatars/8.jpg" },
    orderId: "#ORD-2034",
    product: "DAP Fertilizer (25kg)",
    qty: 10,
    orderDate: "12 July 2025",
    total: "PKR 23,000",
    status: "Pending",
  },
];